### PR TITLE
Refactored LogRaw to not use variable length array

### PR DESCRIPTION
**Pull request by olehermanse**
Prevent overflow in release builds by limiting buflen.
Always allocate buffer of CF_BUFSIZE.
Cleaned up asserts and scope of variables.
Removed pointless 16k constant.
This function is used to print network data, always <= 4096.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5763/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5763/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5763/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5764/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5764/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5764/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5765/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5765/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5765/

**Review by vpodzime — APPROVED** [review]
Looks good to me. But I think the function could just say that at most `CF_BUFSIZE` bytes are logged and if `buflen` is bigger, the log message will end with `...`.

**Comment by olehermanse** [comment]
> Looks good to me. But I think the function could just say that at most `CF_BUFSIZE` bytes are logged and if `buflen` is bigger, the log message will end with `...`.

@vpodzime It could, but I preserved the assert as a `debug_abort_if_reached()` so we don't want anyone to think this function just truncates without removing the abort.

**Pull request merged**
