### PR TITLE
CFE-3292/master: Added GLOB_BRACE support in findfiles()

### PR DESCRIPTION
**Pull request by nickanderson**
Mergetogether: 
https://github.com/cfengine/core/pull/4125

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom please build some packages in Jenkins!

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4910/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4910/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4910/

**Comment by nickanderson** [comment]
@cf-bottom test this in jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4916/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4916/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4916/

**Comment by nickanderson** [comment]
@cf-bottom test this in jenkins, again, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4917/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4917/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4917/

**Comment by olehermanse** [comment]
@nickanderson on windows, we have our own implementation of glob. There are too options:

1) Use a macro to add support for UNIX only (easy).
2) Implement brace globbing in C code on windows (enterprise repo).

I would maybe prefer 2, but YMMV.

**Comment by vpodzime** [comment]
> I would maybe prefer 2, but YMMV.

Same here.

**Comment by nickanderson** [comment]
I also have a preference for #2, but I think that's beyond my skill level, so this thing would go back to the backlog until it were prioritized.

**Comment by olehermanse** [comment]
Closing as we wait until someone has time to impement for windows.

**Pull request closed without merging**
