### PR TITLE
Inline simple functions in string_lib.c

### PR DESCRIPTION
**Pull request by larsewi**
Ticket: CFE-3652
Changelog: None
Signed-off-by: larsewi <lars.erik.wik@northern.tech>

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please !

**Comment by larsewi** [comment]
These optimizations resulted in a speed-up of approx 1%. Please see ticket [CFE-3652](https://tracker.mender.io/browse/CFE-3652).

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6814/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6814/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6814/

**Comment by larsewi** [comment]
@cf-bottom Jenkins again please!

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6821/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6821/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6821/

**Pull request closed without merging**
