### PR TITLE
Added possibility to compile without PCRE support

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, with exotics, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4587/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4587/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4587/

**Comment by olehermanse** [comment]
Wait for: https://github.com/cfengine/libntech/pull/52

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4588/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4588/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4588/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4597/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4597/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4597/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4634/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4634/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4634/

**Comment by olehermanse** [comment]
> I still think the missing PCRE support should also be reflected in the header files. And I still think the error GCC attribute is a perfect fit:

@vpodzime I can't really use `WITH_PCRE` in headers currently, because this macro won't be defined when included from outside of libntech, (without first including libntech config.h). Making sure libntech exports the correct `LDFLAGS`, `CPPFLAGS`, `CFLAGS` is a good way to make this happen, but outside of scope, for now, IMO.

**Pull request merged**
