### PR TITLE
hash.c, json.c: Replace trivial switch with if statements

### PR DESCRIPTION
**Pull request by lluiscampos**
Gets the rid of LGTM alerts.

### CODE REVIEW

**Comment by lluiscampos** [comment]
Note that I decided to keep [the one at mustache.c](https://lgtm.com/projects/g/cfengine/libntech/snapshot/1fd698ca8d34e7eb33db755e3842e16e71386400/files/libutils/mustache.c?sort=name&dir=ASC&mode=heatmap#L779) in purpose. In that specific instance, the switch statement helps readability in the context of the other parts of the function.

**Comment by olehermanse** [comment]
@cf-bottom please test this in Jenkins, just in case.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5239/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5239/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5239/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5244/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5244/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5244/

**Pull request merged**
