### PR TITLE
Added nt_static_assert_string_equal()

### PR DESCRIPTION
**Pull request by olehermanse**
```
nt_static_assert_string_equal(PATH_SEPARATOR, "/");
```

Is more readable than:

```
nt_static_assert(strcmp(PATH_SEPARATOR, "/") == 0);
```

Also added tests for both.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5997/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5997/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5997/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5998/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5998/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5998/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5999/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5999/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5999/

**Review by lluiscampos — APPROVED** [review]

**Review by vpodzime — APPROVED** [review]
Looks good to me. I assume compilers are clever enough to actually compare the strings and not address of `strcmp()` to the address of the string literal or anything like that.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6000/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6000/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6000/

**Review by vpodzime — APPROVED** [review]
Not quite sure it makes sense to add commented-out code with a TODO to uncomment. But I leave that decision to you.

**Comment by olehermanse** [comment]
@vpodzime Thanks, i was unsure as well. I'd like to work towards compiling with C11 flag, updating our compilers and enabling this, so I'll merge it.

**Pull request merged**
