### PR TITLE
ENT-4829: Added possibility to not terminate last line of CSV writer

### PR DESCRIPTION
**Pull request by olehermanse**
Useful for writing "single line csv", for use in reporting protocol.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom, jenkins.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4602/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4602/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4602/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4603/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4603/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4603/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4604/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4604/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4604/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4606/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4606/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4606/

**Pull request merged**
