### PR TITLE
Changed last occurence of `open` to `safe_open`

### PR DESCRIPTION
**Pull request by karlhto**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4117/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4117/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4117/

**Comment by olehermanse** [comment]
@karlhto 

**Jenkins failure:**

This fails in jenkins, because `libcompat/Makefile.am` would need more adjustments to be able to include all parts of libutils.

`libcompat/Makefile.am`:

```
noinst_LTLIBRARIES = libcompat.la

AM_CPPFLAGS = -I$(top_srcdir)/libutils            # platform.h

libcompat_la_LIBADD = $(LTLIBOBJS)
```

`libutils/Makefile.am`:

```
noinst_LTLIBRARIES = libutils.la

# TODO remove the openssl dependency! It's only there for base64 encoding.
AM_CFLAGS   = $(CORE_CFLAGS)   $(PCRE_CFLAGS)   $(OPENSSL_CFLAGS)
AM_CPPFLAGS = $(CORE_CPPFLAGS) $(PCRE_CPPFLAGS) $(OPENSSL_CPPFLAGS)
AM_LDFLAGS  = $(CORE_LDFLAGS)  $(PCRE_LDFLAGS)  $(OPENSSL_LDFLAGS)

libutils_la_LIBADD = ../libcompat/libcompat.la
libutils_la_LIBS   = $(PCRE_LIBS) $(OPENSSL_LIBS)
```

It would at least need the `PCRE_CPPFLAGS`.

**libcompat vs libutils:**

Furthermore, I'm not sure we want this. We haven't talked that much about it, but I think libcompat should not have dependencies from libutils (apart from the necessary config.h / platform.h). Let's discuss this more in person.

**Other occurences of open():**

There are also a few more that you missed, for example in `libcompat/openat.c`.

**Comment by olehermanse** [comment]
Closing, we don't want to add more dependencies on libutils in libcompat.

**Pull request closed without merging**
