### PR TITLE
Two fixes for requiring libsystemd for structured logging

### PR DESCRIPTION
**Pull request by vpodzime**

### CODE REVIEW

**Review by larsewi — APPROVED** [review]
🚀

**Comment by vpodzime** [comment]
@cf-bottom jenkins with NO TESTS please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9722/)

 [NO TESTS]

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9722/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9722/

**Comment by vpodzime** [comment]
builds on exotics: [Build Status](https://ci.cfengine.com/job/pr-pipeline/9730/)

**Pull request merged**
