### PR TITLE
CFE-3543: Fixed issue with libntech and --enable-fhs

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6027/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6027/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6027/

**Review by craigcomstock — APPROVED** [review]
awesome. thank you!

**Review by craigcomstock — APPROVED** [review]
I tested this change with an aports build on x86_64 and it worked great. No remnants or evidence of libntech anywhere in any directories upon installing, self-bootstrapping, and several agent runs.

**Pull request merged**
