### PR TITLE
CFE-3454: Added nt_static_assert()

### PR DESCRIPTION
**Pull request by olehermanse**
See commit messages and comments for details.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins with exotics, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5742/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5742/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5742/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5743/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5743/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5743/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5744/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5744/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5744/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5745/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5745/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5745/

**Comment by olehermanse** [comment]
@cf-bottom Please start another Jenkins build, now that I have enabled `_Static_assert()`. With exotics, of course.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5746/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5746/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5746/

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
