### PR TITLE
ENT-7195: Fixed underflow when calculating mustache tag content length

### PR DESCRIPTION
**Pull request by KotzaBoss**

### CODE REVIEW

**Comment by KotzaBoss** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6644/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6644/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6644/

**Comment by KotzaBoss** [comment]
The two [while loops](https://github.com/cfengine/libntech/blob/5a28e9545913fcf82a37c2bb28d8d266fb8ba242/libutils/mustache.c#L300-L309) in the end are conceptually "stripping whitespace" left and right of the tag identifier. Shouldnt they be stripping `\n` as well?
#### Input
```
{{
 X
}}
```

#### Equivallent
```
{{ \nX\n}}
```

#### Processing
```
  content
  |
  v
{{ \nX\n}}
  -==-== content_len = 4
```

#### Left "strip"
```
     tag.content
     |
     v
{{ \nX\n}}
     -== content_len == 2
```  

#### Right "strip"
```
     tag.content
     |
     v
{{ \nX\n}}
     - content_len == 1
```

**Review by vpodzime — COMMENTED** [review]
I'm not sure if _mustache_ templating supports things like `{{\nX\n}}`, I'd think it doesn't. This looks good to me.

**Review by olehermanse — CHANGES_REQUESTED** [review]
Seems to me that this fixes a crash which users could encounter, and thus should have a changelog entry.

**Comment by KotzaBoss** [comment]
Is the current commit/pr title an acceptable changelog entry?
Perhaps smth like a simplified `Fixed cf-promises crash when expanding mustache tags` is better?

**Comment by olehermanse** [comment]
> Is the current commit/pr title an acceptable changelog entry?
> Perhaps smth like a simplified `Fixed cf-promises crash when expanding mustache tags` is better?

Yes, that suggestion is better.

**Comment by olehermanse** [comment]
@cf-bottom jenkins again, just in case :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6648/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6648/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6648/

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
