### PR TITLE
Replaced and removed test data in tests/unit/data

### PR DESCRIPTION
**Pull request by olehermanse**
Just some cleanups.

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5995/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5995/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5995/

**Review by vpodzime — APPROVED** [review]
ACK

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
