### PR TITLE
Do not #include platform.h in headers

### PR DESCRIPTION
**Pull request by vpodzime**
platform.h includes config.h which is a default name for any
project's configuration definitions. We could use a more specific
name, but every config.h defines things like PACKAGE_NAME and
thus including two such files results in compilation warnings or
errors.

The general rule is that only .c files should include
config.h. When built and installed, the library should provide
library files (static or dynamic) and headers defining the API,
but not config.h.

### CODE REVIEW

**Comment by olehermanse** [comment]
@vpodzime makes sense to me, have you taken a look at core yet? I expect more changes will be needed there.

**Comment by vpodzime** [comment]
@cf-bottom jenkins with exotics and NO TESTS, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9837/)

(with exotics) [NO TESTS]

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9837/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9837/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9838/)

(with exotics) [NO TESTS]

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9838/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9838/

**Comment by vpodzime** [comment]
> @vpodzime makes sense to me, have you taken a look at core yet? I expect more changes will be needed there.

We only need to fix the places that relied on the buggy `#include <platform.h>` in some headers here in *libntech*. But we don't need to make the same changes there as we did here, *core* is not a library.

**Review by larsewi — APPROVED** [review]

**Pull request merged**
